/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PlayerTD[MAX_PLAYERS][16];

//Textdraws

//Player Textdraws
PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 320.000000, 130.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.999999, 22.000003);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 358.500000, 449.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 757935615);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 97.000000, 132.000000, "Preview_Model");
PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 5);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 86.000000, 86.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], -294500353);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 255);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][1], -10.000000, 0.000000, -20.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][1], 1, 1);

PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 187.000000, 132.000000, "Preview_Model");
PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 5);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 86.000000, 86.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], -294500353);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 255);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][2], -10.000000, 0.000000, -20.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][2], 1, 1);

PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 277.000000, 132.000000, "Preview_Model");
PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 5);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 86.000000, 86.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][3], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], -294500353);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 255);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][3], -10.000000, 0.000000, -20.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][3], 1, 1);

PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 367.000000, 132.000000, "Preview_Model");
PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 5);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 86.000000, 86.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][4], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], -294500353);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 255);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][4], -10.000000, 0.000000, -20.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][4], 1, 1);

PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 457.000000, 132.000000, "Preview_Model");
PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 5);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 86.000000, 86.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][5], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], -294500353);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 255);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][5], -10.000000, 0.000000, -20.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][5], 1, 1);

PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 97.000000, 222.000000, "Preview_Model");
PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 5);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 86.000000, 86.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][6], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], -294500353);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 255);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][6], -10.000000, 0.000000, -20.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][6], 1, 1);

PlayerTD[playerid][7] = CreatePlayerTextDraw(playerid, 187.000000, 222.000000, "Preview_Model");
PlayerTextDrawFont(playerid, PlayerTD[playerid][7], 5);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][7], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][7], 86.000000, 86.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][7], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][7], -294500353);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][7], 255);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][7], -10.000000, 0.000000, -20.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][7], 1, 1);

PlayerTD[playerid][8] = CreatePlayerTextDraw(playerid, 277.000000, 222.000000, "Preview_Model");
PlayerTextDrawFont(playerid, PlayerTD[playerid][8], 5);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][8], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][8], 86.000000, 86.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][8], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][8], -294500353);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][8], 255);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][8], -10.000000, 0.000000, -20.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][8], 1, 1);

PlayerTD[playerid][9] = CreatePlayerTextDraw(playerid, 367.000000, 222.000000, "Preview_Model");
PlayerTextDrawFont(playerid, PlayerTD[playerid][9], 5);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][9], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][9], 86.000000, 86.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][9], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][9], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][9], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][9], -294500353);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][9], 255);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][9], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][9], 0);
PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][9], -10.000000, 0.000000, -20.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][9], 1, 1);

PlayerTD[playerid][10] = CreatePlayerTextDraw(playerid, 457.000000, 222.000000, "Preview_Model");
PlayerTextDrawFont(playerid, PlayerTD[playerid][10], 5);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][10], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][10], 86.000000, 86.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][10], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][10], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][10], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][10], -294500353);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][10], 255);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][10], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][10], 0);
PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][10], -10.000000, 0.000000, -20.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][10], 1, 1);

PlayerTD[playerid][11] = CreatePlayerTextDraw(playerid, 97.000000, 309.000000, "PANEL_NAME");
PlayerTextDrawFont(playerid, PlayerTD[playerid][11], 3);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][11], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][11], 220.000000, -16.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][11], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][11], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][11], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][11], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][11], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][11], 0);

PlayerTD[playerid][12] = CreatePlayerTextDraw(playerid, 517.000000, 313.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][12], 0.600000, 1.200002);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][12], 298.500000, 46.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][12], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][12], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][12], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][12], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][12], 731415807);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][12], 0);

PlayerTD[playerid][13] = CreatePlayerTextDraw(playerid, 517.000000, 313.000000, "10/10");
PlayerTextDrawFont(playerid, PlayerTD[playerid][13], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][13], 0.300000, 1.200000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][13], 12.000000, 27.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][13], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][13], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][13], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][13], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][13], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][13], 0);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][13], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][13], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][13], 1);

PlayerTD[playerid][14] = CreatePlayerTextDraw(playerid, 537.000000, 313.000000, ">");
PlayerTextDrawFont(playerid, PlayerTD[playerid][14], 3);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][14], 0.300000, 1.200000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][14], 10.000000, 6.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][14], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][14], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][14], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][14], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][14], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][14], 0);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][14], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][14], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][14], 1);

PlayerTD[playerid][15] = CreatePlayerTextDraw(playerid, 497.000000, 313.000000, "<");
PlayerTextDrawFont(playerid, PlayerTD[playerid][15], 3);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][15], 0.300000, 1.200000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][15], 10.000000, 6.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][15], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][15], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][15], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][15], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][15], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][15], 0);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][15], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][15], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][15], 1);

